config/routes.rb
Rails.application.routes.draw do
  resources :locals

end

app/models/local.rb
class Local < ActiveRecord::Base
end

app/models/local/city.rb
### 市级
class Local::City < Local
  has_many :districts, class_name: "Local::District", foreign_key: :parent_id
  belongs_to :contuny, class_name:  "Local::Province", foreign_key: :parent_id
end

app/models/local/contuny.rb
### 国家
class Local::Contuny < Local
  has_many :provinces, class_name: "Local::Province", foreign_key: :parent_id

end

app/models/local/district.rb
### 区/县城
class Local::District < Local
  has_many :streets, class_name: "Local::Street", foreign_key: :parent_id

  belongs_to :city, class_name: "Local::City", foreign_key: :parent_id
end

app/models/local/province.rb
### 省
class Local::Province < Local
  has_many :cities, class_name: "Local::City", foreign_key: :parent_id
end

app/models/local/street.rb
### 街道
class Local::Street < Local

  belongs_to :district, class_name: "Local::District", foreign_key: :parent_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locals_controller.rb
class LocalsController < ApplicationController
  before_action :set_local, only: [:show, :edit, :update, :destroy]

  # GET /locals
  # GET /locals.json
  def index
    @locals = Local.all
    @locals = @locals.paginate(:page => params[:page], :per_page => params[:per_page])

  end

  # GET /locals/1
  # GET /locals/1.json
  def show
  end

  # GET /locals/new
  def new
    @local = Local.new
  end

  # GET /locals/1/edit
  def edit
  end

  # POST /locals
  # POST /locals.json
  def create
    @local = Local.new(local_params)

    respond_to do |format|
      if @local.save
        format.html { redirect_to @local, notice: 'Local was successfully created.' }
        format.json { render :show, status: :created, location: @local }
      else
        format.html { render :new }
        format.json { render json: @local.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locals/1
  # PATCH/PUT /locals/1.json
  def update
    respond_to do |format|
      if @local.update(local_params)
        format.html { redirect_to @local, notice: 'Local was successfully updated.' }
        format.json { render :show, status: :ok, location: @local }
      else
        format.html { render :edit }
        format.json { render json: @local.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locals/1
  # DELETE /locals/1.json
  def destroy
    @local.destroy
    respond_to do |format|
      format.html { redirect_to locals_url, notice: 'Local was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_local
      @local = Local.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def local_params
      params.require(:local).permit(:name, :type, :parent_id, :abbr)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locals/_form.html.erb
<%= form_for(@local) do |f| %>
  <% if @local.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@local.errors.count, "error") %> prohibited this local from being saved:</h2>

      <ul>
      <% @local.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br>
    <%= f.number_field :parent_id %>
  </div>
  <div class="field">
    <%= f.label :abbr %><br>
    <%= f.text_field :abbr %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locals/edit.html.erb
<h1>Editing Local</h1>

<%= render 'form' %>

<%= link_to 'Show', @local %> |
<%= link_to 'Back', locals_path %>

app/views/locals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Locals</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Type</th>
      <th>Parent</th>
      <th>Abbr</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% n = 0%>
    <% @locals.each do |local| %>
      <tr>
        <td><%= n = n+1 %></td>
        <td><%= local.id %></td>
        <td><%= local.name %></td>
        <td><%= local.type %></td>
        <td><%= local.parent_id %></td>
        <td><%= local.abbr %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @locals %>

<br>

<%= link_to 'New Local', new_local_path %>

app/views/locals/new.html.erb
<h1>New Local</h1>

<%= render 'form' %>

<%= link_to 'Back', locals_path %>

app/views/locals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @local.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @local.type %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @local.parent_id %>
</p>

<p>
  <strong>Abbr:</strong>
  <%= @local.abbr %>
</p>

<%= link_to 'Edit', edit_local_path(@local) %> |
<%= link_to 'Back', locals_path %>